export const ListaFunk = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2021_vKXzXy.jpg",
    link: "https://drive.google.com/uc?export=download&id=1JyKc0CYlSHHuJcNDHHH9jnglH6BCna2T",
    genre: "Funk",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2019_NRhXju.jpg",
    link: "https://drive.google.com/uc?export=download&id=1mtZb3OphG8uznyzn9jU2iOIeUNcRa-FV",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2020_kFbc0t.jpg",
    link: "https://drive.google.com/uc?export=download&id=191sk0ObudgyB_1-LfK5nc6NgPoB3nWV7",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2018_vu5SE3.jpg",
    link: "https://drive.google.com/uc?export=download&id=17GBP8ZFSctq1CUBxGKkEkXuYkSh7qkpy",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2012_r7s1Lo.jpg",
    link: "https://drive.google.com/uc?export=download&id=1hCHCbKNH9FofgONOXDOGYXBPEKk5515M",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 6,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%209_5r30YM.jpg",
    link: "https://drive.google.com/uc?export=download&id=1DZrnZF6U4XyiRVGY5TLCvoGJ-Xgn2fWk",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 7,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2013_q5vucz.jpg",
    link: "https://drive.google.com/uc?export=download&id=1_6IxUNEspozz5PnzmbgZASC6vwyg54gB",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 8,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2014_lQyU76.jpg",
    link: "https://drive.google.com/uc?export=download&id=16tiXIHkoMB7NVAWvJnj9dOtrAqFsQiVz",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 9,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/THEEE%20FUNKK_D9mMtL.jpg",
    link: "https://drive.google.com/uc?export=download&id=1AWmp3o2D0YVLkrvsPQmCOMtbhhAPqLmp",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 10,
    image:
      "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/baixar%20psd%20-%20como%20fazer%20flyer%20-%20flyer%20funk%20-%20psd%20funk%20-%20template%20-%20psd%20agenda%20semanal%20-%20psd%20agenda%20-%20flyer%20artista%20-%20designi%20-%20psd%20free%20-%20psd%20edit%C3%A1vel%20-%20png%20-%20icon%20instragram%20-%20designer%20premium%20-%20psd%20flyer%20-%20canva32_4kYTBn.jpg",
    link: "https://drive.google.com/uc?export=download&id=1FW31ANtbsVzBUcpFILN5JG2KrFtNQOCm",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 11,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/proximos%20shows%20copiar_17H3eQ.jpg",
    link: "https://drive.google.com/uc?export=download&id=1y3VQdjX4hwTBhNvpVO0MtIYeo_PTuLZP",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 12,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/VIBEZINHAA_ysz58Z.jpg",
    link: "https://drive.google.com/uc?export=download&id=1QXy3Ncvkz6Mx8zFB7bTd7gK4cSos5fAB",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 13,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ROLEZADA_KYMm5o.jpg",
    link: "https://drive.google.com/uc?export=download&id=1meTeakHlIUf_Fns784xksY23LLYhkwLg",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 14,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/RETRO%20VIBES_gCxt62.jpg",
    link: "https://drive.google.com/uc?export=download&id=1k57ZM8_DKKxA1sKFd5pxA5QK_rMX8B92",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 15,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/EXCLUSIVE%20FESTIVAL_ElH6fy.jpg",
    link: "https://drive.google.com/uc?export=download&id=19Nztp0II0QYaQVBcn-7amckTgimErMNY",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 16,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/AGENDA%20SEMANAL%20DJ%20CHAPEUZINHO_MJdxlV.jpg",
    link: "https://drive.google.com/uc?export=download&id=1MX7I3d7-c52Tg_shyg3BX3tcZhAXmLF6",
    genre: "Funk",
    status: "fechado",
  },
  {
    id: 17,
    image:
      "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/baixar%20psd%20-%20como%20fazer%20flyer%20-%20flyer%20funk%20-%20psd%20funk%20-%20template%20-%20psd%20agenda%20semanal%20-%20psd%20agenda%20-%20flyer%20artista%20-%20designi%20-%20psd%20free%20-%20psd%20edit%C3%A1vel%20-%20png%20-%20icon%20instragram%20-%20designer%20premium%20-%20psd%20flyer%20-%20canva2_uoG1X8.jpg",
    link: "https://drive.google.com/uc?export=download&id=1H3-XrimREHmK5OusQMZr671CbNP4M8_x",
    genre: "Funk",
    status: "fechado",
  },
];

export const ListaGospel = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2015_xNvPf0.jpg",
    link: "https://drive.google.com/uc?export=download&id=1VDZx7OO2MQOXscaotdoqi2cXemUyN6EM",
    genre: "Gospel",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2016_5uJZef.jpg",
    link: "https://drive.google.com/uc?export=download&id=17NSHLwGZP8ntlf732V4vxUQoFu_zXi3L",
    genre: "Gospel",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2017_82spF0.jpg",
    link: "https://drive.google.com/uc?export=download&id=1ZNuFgaR9TJ6M8vohzRjTs4Gh61LvptcQ",
    genre: "Gospel",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2014_ScXjyS.jpg",
    link: "https://drive.google.com/uc?export=download&id=1Hyjy40M-2DaBBcFklgPPZgHvgE25EjCy",
    genre: "Gospel",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ASFA_8PzDnc.jpg",
    link: "https://drive.google.com/uc?export=download&id=1owAN3VRu1dYX2NT3nk2p-gJU7Akzegw0",
    genre: "Gospel",
    status: "fechado",
  },
  {
    id: 6,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ENCONTROO_a60jZL.jpg",
    link: "https://drive.google.com/uc?export=download&id=1wZJ5m0Oo-rALO7sPbme5UDmM6bDS6Ydu",
    genre: "Gospel",
    status: "fechado",
  },
  {
    id: 7,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/GOSPELLL_O0ysis.jpg",
    link: "https://drive.google.com/uc?export=download&id=1S38dBSUgffLnUPlHz5UAk4x-AFgo4FFR",
    genre: "Gospel",
    status: "fechado",
  },
];

export const ListaSertanejo = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ASADAS_MQ3eM6.jpg",
    link: "https://drive.google.com/uc?export=download&id=193wZv7NKpENDvqcJ5kR1Q17JwvDSbHnR",
    genre: "Sertanejo",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2013_UYI5AT.jpg",
    link: "https://drive.google.com/uc?export=download&id=1h988S4OnKXAt_7aCPMhk2zy2RHYANNPh",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2010_BqnHsJ.jpg",
    link: "https://drive.google.com/uc?export=download&id=1F9SSgMBKUnNQBRdHFn7HPWBhHqSMIUUH",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2012_3nxEJt.jpg",
    link: "https://drive.google.com/uc?export=download&id=1Ua9EqE3ArO2-3LehdkPLxVs-r1IB0CsL",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2012_8NNPNg.jpg",
    link: "https://drive.google.com/uc?export=download&id=1uVuVYPjmLFnXXiB-UrVPfppeO8kAakrv",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 6,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/FORR%C3%93%20TATYY_K6jBtz.jpg",
    link: "https://drive.google.com/uc?export=download&id=1sdrvScwlCWdiPwZNmADP5RfYdA0e2NkR",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 7,
    image:
      "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/baixar%20psd%20-%20como%20fazer%20flyer%20-%20flyer%20funk%20-%20psd%20funk%20-%20template%20-%20psd%20agenda%20semanal%20-%20psd%20agenda%20-%20flyer%20artista%20-%20designi%20-%20psd%20free%20-%20psd%20edit%C3%A1vel%20-%20png%20-%20icon%20instragram%20-%20designer%20premium%20-%20psd%20flyer%20-%20canva3_CGX7r5.jpg",
    link: "https://drive.google.com/uc?export=download&id=1zY777BeWk-CXq0gmXNog5iOdCo2sa5Po",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 8,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/PISEIRO%20BEACH_TSsR13.jpg",
    link: "https://drive.google.com/uc?export=download&id=1h--nR3v4RX5hYwqcXmfEK7hyObflyEVW",
    genre: "Sertanejo",
    status: "fechado",
  },
  {
    id: 9,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/FORR%C3%93%20NEJO_LU0Yzl.jpg",
    link: "https://drive.google.com/uc?export=download&id=1xDjVHyM9c9YX4O7jj4-zSPv29lnM19z1",
    genre: "Sertanejo",
    status: "fechado",
  },
];

export const ListaPagode = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/QWEQWE_ACNR1f.jpg",
    link: "https://drive.google.com/uc?export=download&id=1ouJcne355aPEupWqeKcxc0ZZL9cEeMPG",
    genre: "Pagode",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2015_tT3ZoV.jpg",
    link: "https://drive.google.com/uc?export=download&id=1xbOKCciictKrVKX40N9fSMcmAYqEACrP",
    genre: "Pagode",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2011_GZ2L2d.jpg",
    link: "https://drive.google.com/uc?export=download&id=1FQV7DBAv9SEPzIHQiWGMTOdnpZaV_tFE",
    genre: "Pagode",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2011_89xKIn.jpg",
    link: "https://drive.google.com/uc?export=download&id=1hR6B4Egeab4gvuffbJ6hRu25f8PkBoXQ",
    genre: "Pagode",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/PAGODE%20PREMIUMMM_5XZN4S.jpg",
    link: "https://drive.google.com/uc?export=download&id=1jCXkqWGeZYUR6_sbWRONCp9fh5xpi_ai",
    genre: "Pagode",
    status: "fechado",
  },
  {
    id: 6,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/toca%20o%20som_2ViTDq.jpg",
    link: "https://drive.google.com/uc?export=download&id=1Hqkv-hQr3fo6xAK3M0j2-OwZ2OSKSnHR",
    genre: "Pagode",
    status: "fechado",
  },
  {
    id: 7,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/sunset_6vR7yp.jpg",
    link: "https://drive.google.com/uc?export=download&id=1_jPAvaG__jKcxxrhQ2hbYor2VoucunWB",
    genre: "Pagode",
    status: "fechado",
  },
];

export const ListaFestaJunina = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2012_vHZcnc.jpg",
    link: "https://drive.google.com/uc?export=download&id=126dfncAwe8NEYH41aIfo8tmOQCoT4B1j",
    genre: "Festa Junina",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2013_V37rkL.jpg",
    link: "https://drive.google.com/uc?export=download&id=1_akehWxnj5sgxWXyd8wRLUf2rxQHrJe3",
    genre: "Festa Junina",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2014_AQm41T.jpg",
    link: "https://drive.google.com/uc?export=download&id=1esspPWhu-U8GGRYFRN9945dtngkrIKfm",
    genre: "Festa Junina",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-05-30%20at%2022_Q4xXjy.jpeg",
    link: "https://drive.google.com/uc?export=download&id=15GJXFDZrIyikjn0OReRrMgrgFaWHm0SU",
    genre: "Festa Junina",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-05-30%20at%2022_VHrEFP.jpeg",
    link: "https://drive.google.com/uc?export=download&id=1hWEPIIsn-akCOeQq1t2dRVnKXcrHsJAS",
    genre: "Festa Junina",
    status: "fechado",
  },
];

export const ListaRock = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2014_7ROMRq.jpg",
    link: "https://drive.google.com/uc?export=download&id=1GiT4rwjaQT534zNbLrEFe4kgOtKvh7cK",
    genre: "Rock",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ROCK%20AND%20ROLL_YIPOn6.jpg",
    link: "https://drive.google.com/uc?export=download&id=1qVoZOHZOsfhq7NRFbae2Xq0zATTSq2P_",
    genre: "Rock",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2012_Pk6FQY.jpg",
    link: "https://drive.google.com/uc?export=download&id=1gODThSBTaA0bwpYdOhbkyXBo7r5JUvIg",
    genre: "Rock",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2010_egKIVe.jpg",
    link: "https://drive.google.com/uc?export=download&id=1KxNA-WHEnLtvuGUSMrvXXSTlm_Z8KBdK",
    genre: "Rock",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%209_kx9YuF.jpg",
    link: "https://drive.google.com/uc?export=download&id=1Btiu9o9uxrhj8i68QeyP_SRO7gx3Hz2Q",
    genre: "Rock",
    status: "fechado",
  },
];

export const ListaNamorados = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/Camada%2015_uCsd98.jpg",
    link: "https://drive.google.com/uc?export=download&id=1WBUSKCYUk-FU-MirUEerf1EI_hMccSdC",
    genre: "Namorados",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/DIA%20DOS%20NAMORADOS%20%20(1)_U9IFlC.jpg",
    link: "https://drive.google.com/uc?export=download&id=1pcvZWY8qXXp__dDQhvxxzeJVW7cgzGoD",
    genre: "Namorados",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/DIA%20DOS%20NAMORADOS%20%20(2)_AkFno8.jpg",
    link: "https://drive.google.com/uc?export=download&id=148lhdFCuio72PB71tqPAXL-VdRwOQNnB",
    genre: "Namorados",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/DIA%20DOS%20NAMORADOS%20%20(3)_D61P5E.jpg",
    link: "https://drive.google.com/uc?export=download&id=1Aq3Buugo2WEJkhep8QMXmWb3cN3Kv4SE",
    genre: "Namorados",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/DIA%20DOS%20NAMORADOS%20%20(4)_8jRe42.jpg",
    link: "https://drive.google.com/uc?export=download&id=1ohSENVy9Adr0HxUl2N6KWWsfHolCOyeN",
    genre: "Namorados",
    status: "fechado",
  },
];

export const ListaEletronica = [
  {
    id: 1,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/ELETRO%20PARTYY_m3HFt9.jpg",
    link: "https://drive.google.com/uc?export=download&id=1H_Ty4Od_c9xoawYUINoxxJWOjrIGql4_",
    genre: "Eletrônica",
    status: "aberto",
  },
  {
    id: 2,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-06-27%20at%2010_lvXMiI.jpeg",
    link: "https://drive.google.com/uc?export=download&id=1ipK-LFNWhEfCCx8PlJ0snNkubgmG6RjY",
    genre: "Eletrônica",
    status: "fechado",
  },
  {
    id: 3,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-06-27%20at%2010_YzPQZZ.jpeg",
    link: "https://drive.google.com/uc?export=download&id=1-h-fDelOVdjhoNiqNmoVEEE71PvQdSfu",
    genre: "Eletrônica",
    status: "fechado",
  },
  {
    id: 4,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-06-27%20at%2010_Ax8oTz.jpeg",
    link: "https://drive.google.com/uc?export=download&id=1WYvQSgVeWTiHAXzySyhS2pTTp0GNwmfb",
    genre: "Eletrônica",
    status: "fechado",
  },
  {
    id: 5,
    image: "https://assets.kiwify.com.br/7hSbDx5BmtUuivL/WhatsApp%20Image%202023-06-27%20at%2010_vSaaOH.jpeg",
    link: "https://drive.google.com/uc?export=download&id=1xz_lDkpphjk0JLQKk7XFExocsEqRq_33",
    genre: "Eletrônica",
    status: "fechado",
  },
];
